[workspace]
members = [
    "node",
    "pallets/commitments",
    "pallets/subtensor",
    "runtime",
    "support/macros",
]
resolver = "2"

[workspace.lints.clippy]
indexing-slicing = "deny"
arithmetic-side-effects = "deny"
type_complexity = "allow"
unwrap-used = "deny"

[workspace.dependencies]
cargo-husky = { version = "1", default-features = false }
clap = "4.5.4"
codec = { version = "3.2.2", default-features = false }
enumflags2 = "0.7.9"
futures = "0.3.30"
hex = { version = "0.4", default-features = false }
hex-literal = "0.4.1"
jsonrpsee = { version = "0.22.5", default-features = false }
log = { version = "0.4.21", default-features = false }
memmap2 = "0.9.4"
ndarray = { version = "0.15.6", default-features = false }
parity-util-mem = "0.12.0"
rand = "0.8.5"
scale-info = { version = "2.11.2", default-features = false }
serde = { version = "1.0.199", default-features = false }
serde-tuple-vec-map = { version = "1.0.1", default-features = false }
serde_bytes = { version = "0.11.14", default-features = false }
serde_json = { version = "1.0.116", default-features = false }
serde_with = { version = "=2.0.0", default-features = false }
smallvec = "1.13.2"
litep2p = { git = "https://github.com/paritytech/litep2p", branch = "master" }

subtensor-macros = { path = "support/macros" }

frame-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-benchmarking-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
frame-executive = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-system-benchmarking = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
frame-try-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }

pallet-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-balances = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-membership = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-multisig = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-preimage = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-proxy = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-safe-mode = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-sudo = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-transaction-payment = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
pallet-utility = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }

sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-cli = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-consensus-grandpa-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-chain-spec-derive = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-chain-spec = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-consensus-slots = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-executor = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-keystore = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-network = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-rpc-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-service = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-telemetry = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }

sp-api = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-blockchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sp-consensus-aura = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sp-genesis-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-io = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-keyring = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sp-offchain = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-rpc = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-session = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-std = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-storage = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-timestamp = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
sp-tracing = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-version = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }
sp-weights = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }

sc-consensus-manual-seal = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0", default-features = false }

# Frontier
fp-evm = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fp-rpc = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fp-self-contained = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false, features = [
	"serde",
] }
fp-account = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fc-storage = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fc-db = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fc-consensus = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
fp-dynamic-fee = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }

# Frontier FRAME
pallet-base-fee = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-dynamic-fee = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-ethereum = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-evm = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-evm-chain-id = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-evm-precompile-modexp = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-evm-precompile-sha3fips = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-evm-precompile-simple = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }
pallet-hotfix-sufficients = { git = "https://github.com/gztensor/frontier", branch = "polkadot-v1.11.0-subtensor", default-features = false }

substrate-build-script-utils = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
substrate-fixed = { git = "https://github.com/encointer/substrate-fixed.git", tag = "v0.5.9" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
substrate-wasm-builder = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.11.0" }
frame-metadata = "16"

[patch."https://github.com/paritytech/litep2p"]
litep2p = { git = "https://github.com/gztensor/litep2p", rev = "227791dcb0da8709508fab87d0ea320c49a50ac6" }

#[patch."https://github.com/paritytech/polkadot-sdk.git"]
#sp-io = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-application-crypto = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-runtime = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-keystore = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-core = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-state-machine = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-executor = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-client-api = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#frame-support = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-tracing = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-tracing = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#frame-system = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-transaction-pool = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-timestamp = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-client-db = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-consensus = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-mixnet = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-chain-spec = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-network = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-offchain = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-network-light = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-rpc = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sp-consensus = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-basic-authorship = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }
#sc-consensus-slots = { git = "https://github.com/gztensor/polkadot-sdk", tag = "polkadot-v1.11.0" }

[profile.release]
panic = "unwind"

[profile.test]
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
